name: whatsapp_group_links
description: A new Flutter project.


publish_to: 'none'

version: 3.17.3+17

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  http: any

  cupertino_icons: ^1.0.2
  google_fonts: ^2.0.0-nullsafety.0
  url_launcher:  ^5.4.2

  timeago: 2.0.17

  # facebook_audience_network: ^0.9.0

  admob_flutter: ^1.0.1
  flutter_native_admob: ^2.1.0+3
  get: ^3.24.0

  comment_box: ^0.0.16

  firebase_remote_config: ^0.4.0+2

  # اضافات التطبيق الجديد
  shared_preferences: any
  provider: ^5.0.0

  bottom_navy_bar: ^6.0.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  
  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
